name: Pessimistjolle
favicon: null
layout_spectrum: 0.15133908577263355
typography_spectrum: 0.50279
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.06634673522785306
  lightness: 0.47376898233778775
  saturation: 0.9414732586592436
  rhythmicContrast: 0.5637836698442698
purpose: []
